up:
	docker compose up --build
build:
	docker compose build
logs:
	docker logs hangman-app -f
down:
	docker compose down
full-down:
	docker compose down -v
shell:
	docker exec -it hangman-app bash -i
